wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719343938
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      - 62
      4: 3.12.4
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
mlflow_model:
  desc: null
  value: random_forest_export:prod
test_dataset:
  desc: null
  value: test_data.csv:latest
