name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - requests
  - mlflow
  - pip:
      - wandb
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
